# Generated by Django 4.2.1 on 2023-11-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='allergies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='antecedents_medicaux',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='poids',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
