# Generated by Django 4.2.1 on 2023-11-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_correspondance_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescribe',
        ),
    ]
